# Railway configuration for Rails API backend
# This uses the existing Dockerfile in the preferred_deals_api directory

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
# DATABASE_URL and SECRET_KEY_BASE should be set in Railway dashboard